modLoader="javafml"
loaderVersion="[49,)" 
license="MIT"
issueTrackerURL="https://github.com/willatendo/Simple-Library/issues"

[[mods]]
modId="simplelibrary"
version="3.0.0"
displayName="SimpleLibrary"
displayURL="https://modrinth.com/mod/simple-library"
logoFile="simple_icon.png"
authors="Willatendo"
description='''A simple library for Minecraft!'''

[[dependencies.simplelibrary]]
	modId="forge"
	mandatory=true
	versionRange="[49,)"
	ordering="NONE"
	side="BOTH"
	
[[dependencies.simplelibrary]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.20.4, 1.21)"
	ordering="NONE"
	side="BOTH"
