modLoader="javafml"
loaderVersion="[47,)" 
license="MIT"
issueTrackerURL="https://github.com/willatendo/Simple-Library/issues"

[[mods]]
modId="simplelibrary"
version="0.3.0"
displayName="SimpleLibrary"
authors="Willatendo"
description='''A SimpleLibrary'''

[[dependencies.simplelibrary]]
    modId="forge" 
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.simplelibrary]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"